@echo off
echo Starting Arena Tracker...
cd /d D:\ArenaTracker

echo [1/2] Starting Python backend...
start "Arena Backend" cmd /k "D:\python\python.exe backend/main.py"

echo Waiting for backend to start...
timeout /t 3 /nobreak >nul

echo [2/2] Starting Electron UI...
D:\nodejs\npm.cmd run start
